// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwk0eOXVALou2wvg5cGV7O4ExcrppMY2Q',
    appId: '1:75687481949:web:0439e40512956df793b3b4',
    messagingSenderId: '75687481949',
    projectId: 'saveup-7670d',
    authDomain: 'saveup-7670d.firebaseapp.com',
    storageBucket: 'saveup-7670d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHWRqUzMfnrfvRQTJWS9vJHjyrSrG9-G4',
    appId: '1:75687481949:android:c096d7d82a6f7d7293b3b4',
    messagingSenderId: '75687481949',
    projectId: 'saveup-7670d',
    storageBucket: 'saveup-7670d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpdY32OtZsF9y1ai6VibG7w4KIOTimCw0',
    appId: '1:75687481949:ios:c08fa06cb371dcbe93b3b4',
    messagingSenderId: '75687481949',
    projectId: 'saveup-7670d',
    storageBucket: 'saveup-7670d.firebasestorage.app',
    iosBundleId: 'com.example.saveUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpdY32OtZsF9y1ai6VibG7w4KIOTimCw0',
    appId: '1:75687481949:ios:c08fa06cb371dcbe93b3b4',
    messagingSenderId: '75687481949',
    projectId: 'saveup-7670d',
    storageBucket: 'saveup-7670d.firebasestorage.app',
    iosBundleId: 'com.example.saveUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwk0eOXVALou2wvg5cGV7O4ExcrppMY2Q',
    appId: '1:75687481949:web:89064d86616b1fd693b3b4',
    messagingSenderId: '75687481949',
    projectId: 'saveup-7670d',
    authDomain: 'saveup-7670d.firebaseapp.com',
    storageBucket: 'saveup-7670d.firebasestorage.app',
  );
}
